version: '3.7'


services:
  web:
    container_name: nginx
    build:
      context: app/dockerFiles/nginx
    #    uncommented this line if you have apple silicon proc
    platform: linux/amd64
    ports:
      - "8080:80"
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP:-host.docker.internal}
    volumes:
      - ./:/projectX
    depends_on:
      - php
      - mysql

  php:
    build: ./app/DockerFiles/php
    container_name: php_test
    volumes:
      - ./:/projectX
      - ./app/DockerFiles/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./app/DockerFiles/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    expose:
      - 9000


  mysql:
    container_name: mysql
    #    uncommented this line if you have apple silicon proc
    platform: linux/amd64
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./app/db/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitMq
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "WHATISTHISCOOKIEANDWHY"
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmqpass
      RABBITMQ_DEFAULT_VHOST: "/"


  phpmyadmin:
    container_name: phpmyAdmin
    #    uncommented this line if you have apple silicon proc
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root


  #  mercure:
  #    container_name: mercure_docker_symfony
  #    restart: unless-stopped
  #    image: dunglas/mercure:v0.10.4
  #    environment:
  #      - PUBLISHER_JWT_KEY=mercure_publisher
  #      - SUBSCRIBER_JWT_KEY=mercure_subscriber
  #      - CORS_ALLOWED_ORIGINS=*
  #      - PUBLISH_ALLOWED_ORIGINS=*
  #      - ALLOW_ANONYMOUS=1
  #      - MERCURE_EXTRA_DIRECTIVES=cors_allowed_origins *
  #      - SERVER_NAME=":80"
  #    ports:
  #      - 8001:80
  ###> symfony/mercure-bundle ###

  mercure:
    container_name: mercure
    image: dunglas/mercure
    environment:
      MERCURE_PUBLISHER_JWT_KEY: 'qZwBnfmXLhPRiiHxDayBgTrdydnBdsOT'
      MERCURE_SUBSCRIBER_JWT_KEY: 'qZwBnfmXLhPRiiHxDayBgTrdydnBdsOT'
      SERVER_NAME: ':3000'
      MERCURE_CORS_ALLOWED_ORIGINS: '*'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins "*"
        anonymous 1
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./docker-mercure/Caddyfile.dev:/etc/caddy/Caddyfile.dev
      - ./docker-mercure/Caddyfile:/etc/caddy/Caddyfile